/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BannerGroup: typeof import('./src/components/banner-group/index.vue')['default']
    CountryInfiniteList: typeof import('./src/components/country-infinite-list/index.vue')['default']
    CountryInputGroup: typeof import('./src/components/country-input-group/index.vue')['default']
    CountryList: typeof import('./src/components/country-list/index.vue')['default']
    CountrySearchList: typeof import('./src/components/country-search-list/index.vue')['default']
    MessageNotice: typeof import('./src/components/message-notice/index.vue')['default']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    RechargeCategoryGroup: typeof import('./src/components/recharge-category-group/index.vue')['default']
  }
}
