/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseConfirm: typeof import('./src/components/base-confirm/index.vue')['default']
    BaseHeader: typeof import('./src/components/base-header/index.vue')['default']
    CardAmountList: typeof import('./src/components/card-amount-list/index.vue')['default']
    CountryInfiniteList: typeof import('./src/components/country-infinite-list/index.vue')['default']
    CountryInputGroup: typeof import('./src/components/country-input-group/index.vue')['default']
    CountryList: typeof import('./src/components/country-list/index.vue')['default']
    CountrySearchList: typeof import('./src/components/country-search-list/index.vue')['default']
    EarningsList: typeof import('./src/components/earnings-list/index.vue')['default']
    FlowAmountList: typeof import('./src/components/flow-amount-list/index.vue')['default']
    IndexFocus: typeof import('./src/components/country-input-group/index-focus.vue')['default']
    MessageNotice: typeof import('./src/components/message-notice/index.vue')['default']
    NoticeBar: typeof import('./src/components/notice-bar/index.vue')['default']
    NutActionSheet: typeof import('@nutui/nutui-taro')['ActionSheet']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    PhoneAmountList: typeof import('./src/components/phone-amount-list/index.vue')['default']
    RechargeAccountCell: typeof import('./src/components/recharge-account-cell/index.vue')['default']
    RechargeAccountGroup: typeof import('./src/components/recharge-account-group/index.vue')['default']
    RechargeBaseGroup: typeof import('./src/components/recharge-base-group/index.vue')['default']
    RechargeCategoryGroup: typeof import('./src/components/recharge-category-group/index.vue')['default']
    RechargeCustomGroup: typeof import('./src/components/recharge-custom-group/index.vue')['default']
    RechargeInputGroup: typeof import('./src/components/recharge-input-group/index.vue')['default']
    RechargeList: typeof import('./src/components/recharge-list/index.vue')['default']
    RechargeOperatorGroup: typeof import('./src/components/recharge-operator-group/index.vue')['default']
    RechargePromptCell: typeof import('./src/components/recharge-prompt-cell/index.vue')['default']
    RechargePromptGroup: typeof import('./src/components/recharge-prompt-group/index.vue')['default']
    RechargeTrafficCell: typeof import('./src/components/recharge-traffic-cell/index.vue')['default']
    RechargeTrafficList: typeof import('./src/components/recharge-traffic-list/index.vue')['default']
    WithdrawList: typeof import('./src/components/withdraw-list/index.vue')['default']
  }
}
